Class RestToDll.Production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="RestToDll.Production" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="WS_REST" Category="" ClassName="RestToDll.BS.RestToDll" PoolSize="0" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
